### PR TITLE
Fix product productivity and amount issues

### PR DESCRIPTION
**Pull request by JanSharp**
I did not test this, but I belive it should work
unless you are also using the amount of products somewhere else I am not aware of

### CODE REVIEW

**Comment by JanSharp** [comment]
I just realized that you'd have to migrate existing saves.
It's probably best to write a function to do a full re-translate (and make that available as a command as well)
and call that function in ``on_configuration_changed``

**Comment by JanSharp** [comment]
The more I think about it, I realized that i'm not sure how exactly the products work - if probability is applied first, or min - max …

Do you know? I think it's actually first the probability and then the amount (so it's 50% to get 2, not 2x 50% to get 1 - But i'm not sure, so i'll leave it the way I have it for now)

**Comment by raiguard** [comment]
Thanks for your efforts! Ill merge this when I get home.

The migrations are already at the bottom of control.lua, so it'll automatically update the recipe book and retranslate all dictionaries. I used to have a command for retranslating at any time, but I accidentally removed it and forgot to re-add it when I recently re-wrote the translation module. I'll get that done for the next patch as well.

**Comment by raiguard** [comment]
Looking at the documentation, the probability is the probability of getting anything at all. So for example, you have a 50% chance of getting anywhere from 1-5 products, and 50% chance of getting nothing.

**Comment by JanSharp** [comment]
Alright sounds good - I updated the format to match that - you can change it if you want of course :D

**Comment by raiguard** [comment]
Looks good! 👍 

image

**Pull request merged**
