### PR TITLE
Fluid fixes

### PR DESCRIPTION
**Pull request by kubiix**
Various fixes to fluid temperature support

Proper mark fluid as researched / unresearched
- water is enabled at start if one of offshore pump is enabled at start
before
obrazek
after
obrazek

Fluid as recipe product or offshore pump product
- if product fluid has no temperature, default temperature from fluid will be taken so all products will be with temperature (all debarelling recipes, others and also water from offshore pump)
before
obrazek
after
obrazek
- when only one temperature of fluid exists, use main fluid without temperature (not applicable in PyMods, since all fluids can be voided and for this, temperature range is generated to every fluid)
after
obrazek

Fluid is within range comparsion
- function is_within_range must switch the fluids when the comparsion is for ingredient in recipe

Connecting fluids and recipes
- is now done in second loop for recipes with fluid, after all temerature variants from recipes are known
- this is still not ideal, for example steam from boiler is not processed when building Recipe Book and should be done like offshore pump before recipes

before
obrazek
after
obrazek

Not all changes are optimal in performance aspect and I also need to test it in more complex scenarios. From the quick review it gives me more relevant and correct results, but it is possible that I have broken something.
At least this PR should reveal in detail what in current implementation is missing or not correct

### CODE REVIEW

**Comment by raiguard** [comment]
Thanks for the contribution. I hate to put extra work on you, but could you provide some examples of some specific broken examples that this PR fixes? I would like to find a way to do it without adding an extra loop through all fluids, if at all possible.

**Comment by kubiix** [comment]
Sorry for the late answer, but I was quite busy
I have updated the first post with screenshots with examples
Also fixed few more things I figured today and resolved the conflict

**Comment by kubiix** [comment]
I have one more thing I don't like, but I am not sure now how to handle it:
The fill/empty barrel recipes make mess to researched state of fluids, because when you reseach Fluid handling, all fluids in default temperature becomes researched as product of empty barrel recipe.
But for most of them, to get the fluid in barrel you must fill the barrel with this fluid and you haven't researched it before, you are unable to do it.
Also there is also one strange thing i noticed - you can put fluid of any temperature to the barrel, but when emptying, you will get fluid with default temperature.

**Comment by raiguard** [comment]
> Proper mark fluid as researched / unresearched
This is great, thanks.

> Fluid as recipe product or offshore pump
I didn't like this at first glance, but after looking at it some more, it makes sense. Thanks!

> Fluid is within range comparison
I guess I don't quite understand why this was necessary, but I'll keep staring at it until I figure it out.

> Connecting fluids and recipes
I'll do a more thorough review of this bit in the future.

**Comment by raiguard** [comment]
Thank you for your contribution. I ended up rewriting the fluid temperatures system from scratch to fix the issues you brought up. Like you, I had no choice but to iterate all fluids twice. My solution can be optimized a lot more, but with the full PySuite it seems to run well enough.

**Pull request closed without merging**
