### PR TITLE
Toggle game pause

### PR DESCRIPTION
**Pull request by kubiix**
Added button to pause game while browsing Recipe Book
Not visible in multiplayer
Game is unpaused when main GUI closes
Option to pause game when main GUI opens - default off

!! I did not extend frame-action-icons.png - pause icon is same sprite as for setting in sprite.lua

### CODE REVIEW

**Comment by raiguard** [comment]
I'm OK with this, but I think it would be more intuitive to remove it from the settings list and just have it on the GUI state. Look at Factory Planner as an example. I would also like to do a background dim when paused like FP, but I can tackle that after merging this.

I will add a pause sprite.

**Comment by kubiix** [comment]
I will do the changes you mentioned

**Comment by kubiix** [comment]
I have changed the pause behavior from settings based to remember state when closed
Also added the dimmer, but I can't figure out, how catch the click on the dimmer, to keep the gui on top :(
Last add is quite poor support to sync pause with Factory Planner, it is commented in code

**Comment by raiguard** [comment]
I'll talk with Therenas about adding a remote interface to handle the dimmer frame.

**Comment by raiguard** [comment]
This will not work with the new interaction model that will be in v3, so I'm going to close it. Sorry!

**Pull request closed without merging**
