### PR TITLE
RU locale for RecipeBook v3.0.1

### PR DESCRIPTION
**Pull request by Astorin**

### CODE REVIEW

**Comment by raiguard** [comment]
Thanks, as always! I changed a few strings in v3.0.2, so I decided to wait until you can make those changes before I merge.

**Comment by raiguard** [comment]
image
I'll fix this bug, but I'd recommend removing the English name from this and just keeping the Cyrillic version. Unless there's a reason to have both?

**Comment by Astorin** [comment]
> I'd recommend removing the English name from this and just keeping the Cyrillic version. Unless there's a reason to have both?

It's just for convenience. Both names useful for mod view and search in game settings. You can remove English name and leave Cyrillic if you want. Or you can use other string for GUI caption. You choose.

P.S. Link to mod portal is broken in readme ^_^

**Comment by raiguard** [comment]
Thanks for your contributions! I'll leave the English name in and will fix the stretching bug. :)

**Pull request merged**
