### PR TITLE
Technology page

### PR DESCRIPTION
**Pull request by kubiix**
Added technology page with detail of technology
Added option to search techologies
Click on technology opens detail instead of technology tree
Shift-click opens technology tree

obrazek

### CODE REVIEW

**Comment by raiguard** [comment]
Wow! I wasn't planning on a technology screen, but after looking at it, I actually quite like it. Great job!

**Comment by kubiix** [comment]
I am thinking about two more things
- extending the technology tooltip with research cost info
- on technology page add two more lists with items and fluid, that will become available as products of associated recipes

I am not sure how it will look, but I want to give it try

**Comment by raiguard** [comment]
Oops, already merged. Would you like me to un-merge it, or are you OK with creating another PR?

**Comment by kubiix** [comment]
I can do later another PR, no problem :)

**Comment by kubiix** [comment]
Little Offtopic - what do you think about settings option to merge item and fluid in search combo to one as it was before and query them together? Actually I liked it more

**Comment by raiguard** [comment]
I'm kinda split on it. I liked them combined, but now that they're separate, it's growing on me. Especially when some fluids have lots of temperatures, having them combined with items would make the search results incredibly long.

**Comment by kubiix** [comment]
Now with Enter switches to next type to search, maybe Shift Enter cloud toggle from item to fluid and opposite

**Comment by raiguard** [comment]
I can make shift+enter go back instead of forward. Would that work?

A little more on-topic: I'm going to experiment with improving infinite technologies a bit - adding their ranges to their names and allowing you to flip between the levels. You might run into some merge conflicts with your new PR.

**Pull request merged**
